:Singapore:
  :paths:
    - "/authorize/signup_login"
    - "/authorize/get_token"
    - "/user"
    - "/notify_kyc_callback"
    - "/user/verify"
    - "/user/activities"
    - "/user/transfer_info"
    - "/user/balance_callback"
    - "/notify_callback"
    - "/charges"
    - "/charges/{id}/authorize"
    - "/charges/{id}/cancel"
    - "/charges/{id}"
    - "/charges/{id}/refunds"
    - "/payouts"
    - "/payouts/{id}"
    - "/user/bank_account"
    - "/user/bank_account/{bank_account_id}"
    - "/user/bank_account/{bank_account_id}/withdraw"
    - "/user/bank_account/withdrawal_requests"
    - "/banks"
    - "/notify_withdrawal_callback"
    - "/user/bank_account/withdrawal_requests/{withdrawal_request_id}"
    - "/authorize/hello"
    - "/authorize/get_mock_otp"
    - "/user/verify"
    - "/user/bank_account/withdrawal_requests/mock_result"
    - "/cards*"
    - "/credit_card_charges/charge_card_guest"
    - "/credit_card_charges/charge_card"
    - "/intents*"
    - "/notify_intent_callback"

:Indonesia:
  :paths:
    - "/authorize/signup_login"
    - "/authorize/private_wallet"
    - "/authorize/get_token"
    - "/user"
    - "/notify_kyc_callback"
    - "/user/activities"
    - "/user/transfer_info"
    - "/charges"
    - "/charges/{id}"
    - "/charges/{id}/refunds"
    - "/payouts"
    - "/payouts/{id}"
    - "/user/bank_account"
    - "/user/bank_account"
    - "/user/bank_account/{bank_account_id}"
    - "/user/bank_account/{bank_account_id}/withdraw"
    - "/notify_withdrawal_callback"
    - "/user/bank_account/withdrawal_requests/{withdrawal_request_id}"
    - "/loans"
    - "/notify_loan_callback"
    - "/loans/{id}"
    - "/loans/{id}/disbursement_reports"
    - "/notify_disbursement_report_callback"
    - "/loans/{loan_id}/repayments"
    - "/notify_repayment_callback"
    - "/loans/{loan_id}/repayments/{loan_repayment_id}"
    - "/loans/{loan_id}/repayments"
    - "/loans/reconciliations"
    - "/loans/repayments/reconciliations"
    - "/user/bank_account/withdrawal_requests"
    - "/loans/{loan_id}/disbursements"
    - "/notify_loan_disbursement_callback"
    - "/loans/{loan_id}/disbursements/{id}"
    - "/loans/{loan_id}/disbursements"
    - "/loans_mock/{id}/mocks"
    - "/loans_mock/{id}/repayments/{repayment_id}/mocks"
    - "/authorize/hello"
    - "/authorize/get_mock_otp"
    - "/user/verify"
    - "/user/bank_account/withdrawal_requests/mock_result"
#:doc-name:
#  :paths:
#    - "/pathABC"
#    - "/pathXYZ"
