:Singapore:
  :paths:
    - "/authorize*"
    - "/user"
    - "/user/activities"
    - "/user/transfer_info"
    - "/user/bank_account*"
    - "/charges"
    - "/payouts*"
    - "/banks"
  :tags:
    - "Registration"
    - "User Account"
    - "Charge"
    - "Payout"
    - "Bank Account"
    - "Withdraw"
:Indonesia:
  :paths:
    - "/authorize*"
    - "/user*"
    - "/charges"
    - "/payouts*"
    - "/banks"
    - "/loans*"
  :tags:
    - "Registration"
    - "User Account"
    - "Charge"
    - "Payout"
    - "Bank Account"
    - "Withdraw"
    - "Channeling"
# :Singapore_and_Indonesia:
#   :paths:
#     - "/pet"
#     - "/store/inventory"
#     - "/user"
#   :tags:
#     - "pet"
#     - "store"
#     - "user"
