:Singapore:
  :paths:
    - "/user*"
    - "/user/bank_account/{bank_account_id}/withdraw*"
:Indonesia:
  :paths:
    - "/authorize*"
    - "/user"
    - "/user/bank_account/{bank_account_id}/withdraw"
    - "/loans*"

